#!/usr/bin/env python3
"""
Generate the Neo Genesis Open Knowledge Format (OKF) v0.1 bundle.

OKF v0.1 spec: https://github.com/GoogleCloudPlatform/knowledge-catalog/tree/main/okf
- A bundle is a directory of markdown files with YAML frontmatter.
- One concept = one file; the file path (minus .md) is the concept ID.
- Required frontmatter field: `type`. Recommended: title, description, resource, tags, timestamp.
- index.md = progressive disclosure; log.md = change history. Cross-links = markdown links.

SOURCE: only already-public facts from https://neogenesis.app/llms-full.txt (no secrets, no internal .agent/).
Generated by Neo Genesis (Claude) on 2026-06-16. Knowledge content licensed CC-BY-4.0.
"""
from pathlib import Path

BASE = Path(__file__).resolve().parent
TS = "2026-06-16T00:00:00Z"
OKF_VER = "0.1"

# ---------------------------------------------------------------- data (public)
SBUS = [
    ("ur-wrong", "UR WRONG", "https://ur-wrong.com", "Q139569710",
     "AI debate platform that generates arguments on both sides of a question."),
    ("toolpick", "ToolPick", "https://toolpick.dev", "Q139569711",
     "B2B SaaS comparison engine that analyzes and compares tool stacks."),
    ("reviewlab", "ReviewLab", "https://review.neogenesis.app", "Q139569712",
     "AI product review magazine producing data-driven analysis."),
    ("kott", "K-OTT", "https://kott.kr", "Q139569715",
     "Korean OTT (streaming) recommendation platform."),
    ("whylab", "WhyLab", "https://whylab.neogenesis.app", "Q139569716",
     "Causal inference platform for data analysis."),
    ("ethicaai", "EthicaAI", "https://ethica.neogenesis.app", "Q139569718",
     "AI ethics research project (BETA)."),
    ("finstack", "FinStack", "https://finstack.neogenesis.app", "Q139569720",
     "Fintech tool and API reviews."),
    ("aiforge", "AIForge", "https://aiforge.neogenesis.app", "Q139569724",
     "Enterprise AI solution benchmarks."),
    ("sellkit", "SellKit", "https://sellkit.neogenesis.app", "Q139569725",
     "E-commerce tool reviews."),
    ("deploystack", "DeployStack", "https://deploystack.neogenesis.app", "Q139569726",
     "DevOps platform comparisons."),
    ("craftdesk", "CraftDesk", "https://craftdesk.neogenesis.app", "Q139569727",
     "Design tool reviews."),
]

DATASETS = [
    ("korean-rag-ssot-golden-50", "Korean RAG SSOT Golden 50", "50 tasks",
     "10.5281/zenodo.20018462", "Korean-language retrieval benchmark."),
    ("ethicaai-mixed-safe-evidence", "EthicaAI Mixed-Safe Evidence", "510 rows",
     "10.5281/zenodo.20018466", "Multi-agent safety research data."),
    ("whylab-docker-validation", "WhyLab Docker Validation", "402 episodes",
     "10.5281/zenodo.20018468", "Null-result validation evidence."),
    ("sbu-programmatic-seo-effects", "SBU Programmatic SEO Effects", "35 rows",
     "10.5281/zenodo.20018474", "Single-operator SEO measurements."),
    ("cross-agent-review-queue", "Cross-Agent Review Queue", "37 transcripts",
     "10.5281/zenodo.20018477", "Multi-agent governance evidence."),
    ("korean-llm-citation-baseline", "Korean LLM Citation Baseline", "126 measurements",
     "10.5281/zenodo.20018479", "AI citation pickup across 3 LLMs."),
    ("sora-multi-device-orchestration", "Sora Multi-Device Orchestration", "303 sections",
     "10.5281/zenodo.20018481", "6-device fleet governance patterns."),
    ("quant-v11-ensemble-specs", "Quant v11 Ensemble Specs", "375 sections",
     "10.5281/zenodo.20018487", "Trading alpha designs and kill-switch."),
    ("ai-brand-mention-baseline-2026", "AI Brand Mention Baseline 2026", "486 measurements",
     "", "Longitudinal generative engine optimization measurements."),
]

RESEARCH = [
    ("ethicaai-mixed-safe", "EthicaAI Mixed-Safe Research",
     "Multi-agent AI safety research (manuscript under peer review)."),
    ("whylab-docker-validation", "WhyLab Causal Inference Docker Validation",
     "Docker-based null-result validation of a causal inference method (peer review pending)."),
    ("rag-master-design-v1", "RAG Master Design v1",
     "A 24-week architecture rollout design for retrieval-augmented generation."),
    ("agent-environment-v2", "Agent Environment v2",
     "Multi-agent research patterns and runtime environment design."),
]

# ---------------------------------------------------------------- helpers
def fm(type_, title, description, resource="", tags=None, extra=None):
    lines = ["---", f"type: {type_}", f"title: {title}",
             f"description: {description}"]
    if resource:
        lines.append(f"resource: {resource}")
    if tags:
        lines.append("tags: [" + ", ".join(tags) + "]")
    lines.append(f"timestamp: {TS}")
    if extra:
        for k, v in extra.items():
            lines.append(f"{k}: {v}")
    lines.append("---")
    return "\n".join(lines) + "\n\n"

def write(relpath, content):
    p = BASE / relpath
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

# ---------------------------------------------------------------- root files
write("index.md", fm(
    "Knowledge Bundle", "Neo Genesis — Open Knowledge Format Bundle",
    "Public knowledge about Neo Genesis, expressed in Open Knowledge Format (OKF) v0.1.",
    resource="https://neogenesis.app", tags=["neo-genesis", "okf", "ai"],
    extra={"okf_version": f"\"{OKF_VER}\""}
) + """# Neo Genesis — Open Knowledge Format Bundle

A vendor-neutral, agent- and human-readable bundle of **already-public** facts about Neo Genesis,
expressed in [Open Knowledge Format (OKF) v0.1](https://github.com/GoogleCloudPlatform/knowledge-catalog/tree/main/okf).

## Top-level concepts
- [organization](/organization/index.md) — the company, founder, pipeline, governance, tech stack
- [sbus](/sbus/index.md) — the 11 live business units
- [datasets](/datasets/index.md) — 9 open datasets (CC-BY-4.0)
- [research](/research/index.md) — published research and operational assets

> Source of facts: https://neogenesis.app/llms-full.txt . Knowledge content: CC-BY-4.0.
""")

write("log.md", fm(
    "Change Log", "OKF Bundle Change Log",
    "Chronological change history for this OKF bundle (newest first)."
) + """# Change Log

## 2026-06-16
- v0.1 bundle initial publication. Generated from public neogenesis.app facts; OKF v0.1 conformant.
""")

write("README.md", """# Neo Genesis — Open Knowledge Format (OKF) Bundle

This repository is an [Open Knowledge Format (OKF) v0.1](https://github.com/GoogleCloudPlatform/knowledge-catalog/tree/main/okf)
bundle of **publicly available** knowledge about [Neo Genesis](https://neogenesis.app).

OKF (published by Google Cloud, 2026) represents knowledge as a directory of markdown files with
YAML frontmatter, designed to be consumable by AI agents and readable by humans. One file = one
concept; the file path is the concept ID; cross-links between files form the knowledge graph.

## Contents
- `index.md` — bundle root (progressive disclosure)
- `organization/` — company, founder, HIVE MIND pipeline, V-Score, governance, tech stack
- `sbus/` — the 11 live business units
- `datasets/` — 9 open datasets (CC-BY-4.0)
- `research/` — published research and operational assets
- `log.md` — change history
- `generate_okf_bundle.py` — reproducible generator (public sources only)

## Source & License
All facts are sourced from public pages (https://neogenesis.app/llms-full.txt). No secrets or
internal content are included. Knowledge content is licensed **CC-BY-4.0** (see `LICENSE`).
""")

write("LICENSE", """Creative Commons Attribution 4.0 International (CC BY 4.0)

This OKF knowledge bundle is licensed under the Creative Commons Attribution 4.0
International License. You are free to share and adapt the material for any purpose,
including commercially, provided you give appropriate credit.

Attribution: Neo Genesis (https://neogenesis.app), Wikidata Q139569680.
Full license text: https://creativecommons.org/licenses/by/4.0/legalcode
""")

# ---------------------------------------------------------------- organization
write("organization/index.md", fm(
    "Index", "Organization", "Concepts about Neo Genesis as an organization.",
    resource="https://neogenesis.app", tags=["organization"]
) + """# Organization

- [neo-genesis](/organization/neo-genesis.md)
- [founder-yesol-heo](/organization/founder-yesol-heo.md)
- [hive-mind-pipeline](/organization/hive-mind-pipeline.md)
- [v-score](/organization/v-score.md)
- [governance](/organization/governance.md)
- [tech-stack](/organization/tech-stack.md)
""")

write("organization/neo-genesis.md", fm(
    "Organization", "Neo Genesis", "Single-operator AI company running 11 live business units via the HIVE MIND pipeline.",
    resource="https://neogenesis.app", tags=["company", "ai", "korea"],
    extra={"wikidata": "Q139569680", "founded": "2024", "headquarters": "Seoul, Korea"}
) + """# Neo Genesis (네오제네시스)

Neo Genesis is a single-operator company, founded in **2024** in **Seoul, Korea**, that manages
**11 live business units** through a shared autonomous pipeline called **HIVE MIND**. The system
automates content creation, quality gating, and deployment across all products without human
approval between stages.

- Tagline: "AI Works. You Decide."
- Founder & sole operator: [founder-yesol-heo](/organization/founder-yesol-heo.md)
- Pipeline: [hive-mind-pipeline](/organization/hive-mind-pipeline.md)
- Public contact: help@neogenesis.app
- Wikidata: [Q139569680](https://www.wikidata.org/wiki/Q139569680)
- Business units: [sbus](/sbus/index.md)
""")

write("organization/founder-yesol-heo.md", fm(
    "Person", "Yesol Heo", "Founder and sole operator of Neo Genesis.",
    resource="https://heoyesol.kr", tags=["founder", "person"],
    extra={"wikidata": "Q139569708"}
) + """# Yesol Heo (허예솔)

Yesol Heo is the **founder and sole operator** of [Neo Genesis](/organization/neo-genesis.md),
running 11 business units single-handedly with AI automation.

- Portfolio: https://heoyesol.kr
- Wikidata: [Q139569708](https://www.wikidata.org/wiki/Q139569708)
""")

write("organization/hive-mind-pipeline.md", fm(
    "Process", "HIVE MIND Pipeline", "The 7-stage autonomous content and deployment pipeline used across all SBUs.",
    resource="https://neogenesis.app", tags=["pipeline", "automation", "governance"]
) + """# HIVE MIND Pipeline

A 7-stage autonomous pipeline that runs across all [business units](/sbus/index.md) without human
approval between stages:

1. **Sense** — signal collection
2. **Think** — RLAIF planning
3. **Create** — content generation
4. **Quality** — [V-Score](/organization/v-score.md) >= 184.5 gate
5. **Ship** — Vercel deploy + IndexNow ping
6. **Learn** — engagement tracking
7. **Refresh** — 90-day cycle

See also: [governance](/organization/governance.md), [tech-stack](/organization/tech-stack.md).
""")

write("organization/v-score.md", fm(
    "Metric", "V-Score Quality Gate", "Publication quality threshold used by the HIVE MIND pipeline.",
    resource="https://neogenesis.app", tags=["quality", "metric"]
) + """# V-Score Quality Gate

The publication quality gate used in the [HIVE MIND pipeline](/organization/hive-mind-pipeline.md).

- Formula: **V = 40F + 35E + 15C + 10O** (fact density, EEAT, citations, originality)
- Threshold: **V >= 184.5** required for publication
""")

write("organization/governance.md", fm(
    "Governance", "Governance & Safety", "Owner sovereignty and kill-switch controls over the autonomous fleet.",
    resource="https://neogenesis.app", tags=["governance", "safety"]
) + """# Governance & Safety

- **Sora Orchestrator** governs a 6-device fleet (3 desktops, 1 server, 1 Mac Studio, 2 mobile).
- **Owner Sovereignty (Article 0):** a single human retains override authority over the autonomous system.
- **9-Layer Kill Switch:** layered safety controls over automated actions.

See the [HIVE MIND pipeline](/organization/hive-mind-pipeline.md) for the production flow.
""")

write("organization/tech-stack.md", fm(
    "Technology", "Core Technology Stack", "Primary technologies behind Neo Genesis products and pipeline.",
    resource="https://neogenesis.app", tags=["technology", "stack"]
) + """# Core Technology Stack

- **Frontend:** Next.js 16, React 19, TypeScript
- **Backend:** Python (FastAPI), Prisma
- **AI models:** Gemini, Claude, local LLM support
- **Infrastructure:** Vercel, Supabase, Cloudflare
- **Core systems:** HIVE MIND pipeline, RLAIF reward model, V-Score quality gate
""")

# ---------------------------------------------------------------- sbus
sbu_index = ["# Business Units (SBUs)", "",
             "Neo Genesis runs 11 live business units:", ""]
for sid, name, url, qid, desc in SBUS:
    sbu_index.append(f"- [{sid}](/sbus/{sid}.md) — {name}: {desc}")
write("sbus/index.md", fm(
    "Index", "Business Units", "The 11 live Neo Genesis business units.",
    resource="https://neogenesis.app", tags=["sbus"]
) + "\n".join(sbu_index) + "\n")

for sid, name, url, qid, desc in SBUS:
    write(f"sbus/{sid}.md", fm(
        "Business Unit", name, desc, resource=url, tags=["sbu", "product"],
        extra={"wikidata": qid}
    ) + f"""# {name}

{desc}

- Website: {url}
- Operated by: [neo-genesis](/organization/neo-genesis.md)
- Wikidata: [{qid}](https://www.wikidata.org/wiki/{qid})
""")

# ---------------------------------------------------------------- datasets
ds_index = ["# Open Datasets", "",
            "9 open datasets published on Hugging Face (CC-BY-4.0): https://huggingface.co/neogenesislab", ""]
for did, name, size, doi, desc in DATASETS:
    ds_index.append(f"- [{did}](/datasets/{did}.md) — {name} ({size})")
write("datasets/index.md", fm(
    "Index", "Open Datasets", "Open research datasets published by Neo Genesis.",
    resource="https://huggingface.co/neogenesislab", tags=["datasets"]
) + "\n".join(ds_index) + "\n")

for did, name, size, doi, desc in DATASETS:
    extra = {"size": size, "license": "CC-BY-4.0"}
    if doi:
        extra["doi"] = doi
    write(f"datasets/{did}.md", fm(
        "Dataset", name, desc, resource="https://huggingface.co/neogenesislab",
        tags=["dataset", "open-data"], extra=extra
    ) + f"""# {name}

{desc}

- Size: {size}
- License: CC-BY-4.0
{f"- DOI: {doi}" if doi else ""}
- Publisher: [neo-genesis](/organization/neo-genesis.md) (Hugging Face: neogenesislab)
""")

# ---------------------------------------------------------------- research
res_index = ["# Research & Operational Assets", ""]
for rid, name, desc in RESEARCH:
    res_index.append(f"- [{rid}](/research/{rid}.md) — {name}")
write("research/index.md", fm(
    "Index", "Research", "Published research and operational assets.",
    resource="https://neogenesis.app", tags=["research"]
) + "\n".join(res_index) + "\n")

for rid, name, desc in RESEARCH:
    write(f"research/{rid}.md", fm(
        "Research", name, desc, resource="https://neogenesis.app",
        tags=["research", "cc-by-4.0"]
    ) + f"""# {name}

{desc}

- Producer: [neo-genesis](/organization/neo-genesis.md)
- License: CC-BY-4.0
""")

# ---------------------------------------------------------------- done
count = sum(1 for _ in BASE.rglob("*.md"))
print(f"OKF bundle generated under: {BASE}")
print(f"markdown concept files: {count}")
